SOURCE_FAMILIES = [
    {"family": "baseline_state", "dataset": "Human Cell Atlas", "code": "hca", "implemented": True},
    {"family": "baseline_state", "dataset": "GTEx", "code": "gtex", "implemented": True},
    {"family": "baseline_state", "dataset": "Tabula Sapiens", "code": "tabula_sapiens", "implemented": True},
    {"family": "regulatory_logic", "dataset": "ENCODE", "code": "encode", "implemented": True},
    {"family": "regulatory_logic", "dataset": "Roadmap Epigenomics", "code": "roadmap", "implemented": True},
    {"family": "regulatory_logic", "dataset": "TRRUST", "code": "trrust", "implemented": True},
    {"family": "perturbation_response", "dataset": "Perturb-seq", "code": "perturb_seq", "implemented": True},
    {"family": "perturbation_response", "dataset": "LINCS", "code": "lincs", "implemented": True},
    {"family": "perturbation_response", "dataset": "DepMap", "code": "depmap", "implemented": True},
    {"family": "metabolism_feasibility", "dataset": "Recon3D", "code": "recon3d", "implemented": True},
    {"family": "metabolism_feasibility", "dataset": "BioModels", "code": "biomodels", "implemented": True},
    {"family": "metabolism_feasibility", "dataset": "HMDB", "code": "hmdb", "implemented": True},
    {"family": "spatial_context", "dataset": "HuBMAP", "code": "hubmap", "implemented": True},
    {"family": "spatial_context", "dataset": "CELLxGENE", "code": "cellxgene", "implemented": True},
    {"family": "clinical_outcomes", "dataset": "TCGA", "code": "tcga", "implemented": True},
    {"family": "clinical_outcomes", "dataset": "UK Biobank", "code": "uk_biobank", "implemented": True},
    {"family": "signaling_graph", "dataset": "Reactome", "code": "reactome", "implemented": True},
    {"family": "signaling_graph", "dataset": "KEGG", "code": "kegg", "implemented": True},
    {"family": "signaling_graph", "dataset": "OmniPath", "code": "omnipath", "implemented": True},
]
