CREATE TABLE IF NOT EXISTS cod_event (
    cod_event_id TEXT PRIMARY KEY,
    cod_subject_id TEXT NOT NULL,
    cod_cell_instance_id TEXT NOT NULL,
    cod_parent_event_id TEXT,
    cod_batch_id TEXT NOT NULL,
    cod_release_version TEXT NOT NULL,
    source_dataset TEXT NOT NULL,
    source_family TEXT,
    source_study_id TEXT NOT NULL,
    source_sample_id TEXT NOT NULL,
    source_cell_id TEXT,
    source_assay_id TEXT NOT NULL,
    source_record_pointer TEXT NOT NULL,
    source_accession TEXT,
    source_download_url TEXT,
    source_downloaded_at TEXT,
    source_checksum TEXT,
    source_release_info TEXT,
    processing_pipeline_version TEXT NOT NULL,
    evidence_trace_id TEXT NOT NULL,
    license_class TEXT NOT NULL,
    record_origin_type TEXT NOT NULL,
    species TEXT NOT NULL,
    donor_id_normalized TEXT,
    sex TEXT,
    age TEXT,
    ancestry TEXT,
    health_status TEXT,
    disease_state TEXT,
    disease_ontology_id TEXT,
    tissue_label TEXT NOT NULL,
    uberon_id TEXT,
    cell_type_label TEXT NOT NULL,
    cell_ontology_id TEXT,
    developmental_stage TEXT,
    microenvironment_label TEXT,
    spatial_region_label TEXT,
    time_anchor_type TEXT NOT NULL,
    t0_timestamp TEXT NOT NULL,
    t0_time_unit TEXT NOT NULL,
    delta_t_to_output TEXT,
    delta_t_to_outcome TEXT,
    trajectory_group_id TEXT,
    time_uncertainty_score REAL,
    intervention_present BOOLEAN NOT NULL,
    intervention_type TEXT NOT NULL,
    intervention_target_entity TEXT,
    intervention_target_id TEXT,
    intervention_direction TEXT NOT NULL,
    intervention_dose TEXT,
    intervention_dose_unit TEXT,
    intervention_duration TEXT,
    intervention_delivery_mode TEXT,
    intervention_combo_id TEXT,
    control_definition TEXT,
    has_genome_state BOOLEAN NOT NULL,
    has_epigenome_state BOOLEAN NOT NULL,
    has_transcriptome_state BOOLEAN NOT NULL,
    has_proteome_state BOOLEAN NOT NULL,
    has_phosphoproteome_state BOOLEAN NOT NULL,
    has_metabolome_state BOOLEAN NOT NULL,
    has_spatial_state BOOLEAN NOT NULL,
    has_neighbor_context BOOLEAN NOT NULL,
    has_clinical_context BOOLEAN NOT NULL,
    has_time_series_context BOOLEAN NOT NULL,
    genome_profile_ref TEXT,
    epigenome_profile_ref TEXT,
    transcriptome_profile_ref TEXT,
    proteome_profile_ref TEXT,
    phosphoproteome_profile_ref TEXT,
    metabolome_profile_ref TEXT,
    spatial_profile_ref TEXT,
    neighbor_profile_ref TEXT,
    state_embedding_ref TEXT,
    state_summary_ref TEXT,
    external_signal_set_ref TEXT,
    resource_state_ref TEXT,
    stress_state_ref TEXT,
    cell_cycle_state TEXT,
    mitochondrial_state TEXT,
    damage_response_state TEXT,
    senescence_state TEXT,
    immune_context_ref TEXT,
    constraint_profile_ref TEXT,
    pre_state_ref TEXT,
    post_state_ref TEXT,
    intervention_ref TEXT,
    constraint_refs TEXT,
    reward_context_ref TEXT,
    measured_state_flag BOOLEAN NOT NULL,
    harmonized_state_flag BOOLEAN NOT NULL,
    inferred_state_flag BOOLEAN NOT NULL,
    probabilistic_linkage_flag BOOLEAN NOT NULL,
    action_level_0 TEXT NOT NULL,
    action_level_1 TEXT NOT NULL,
    action_level_2 TEXT NOT NULL,
    action_label_set_ref TEXT NOT NULL,
    action_primary_label TEXT NOT NULL,
    action_intensity_score REAL NOT NULL,
    action_directionality TEXT NOT NULL,
    action_zone TEXT NOT NULL,
    action_confidence_score REAL NOT NULL,
    action_assignment_method TEXT NOT NULL,
    short_horizon_output_ref TEXT,
    differential_expression_signature_ref TEXT,
    differential_protein_signature_ref TEXT,
    differential_metabolite_signature_ref TEXT,
    secretome_signature_ref TEXT,
    morphology_signature_ref TEXT,
    viability_measure TEXT,
    proliferation_measure TEXT,
    output_confidence_score REAL,
    long_horizon_outcome_ref TEXT,
    fate_outcome_label TEXT,
    tissue_outcome_label TEXT,
    therapy_response_label TEXT,
    disease_progression_label TEXT,
    survival_proxy TEXT,
    outcome_time_horizon TEXT,
    outcome_confidence_score REAL,
    reward_context_label TEXT,
    candidate_reward_variables_ref TEXT,
    fitness_proxy_score REAL,
    homeostasis_proxy_score REAL,
    immune_function_proxy_score REAL,
    reward_inference_method TEXT,
    raw_qc_score REAL,
    harmonization_qc_score REAL,
    batch_correction_flag BOOLEAN NOT NULL,
    imputation_flag BOOLEAN NOT NULL,
    deconvolution_flag BOOLEAN NOT NULL,
    modality_conflict_flag BOOLEAN NOT NULL,
    manual_review_flag BOOLEAN NOT NULL,
    exclusion_reason TEXT,
    state_representation_type TEXT NOT NULL,
    assay_distortion_notes_ref TEXT,
    measurement_support_score REAL,
    causal_evidence_tier INTEGER NOT NULL,
    causal_support_ref TEXT,
    replication_count INTEGER,
    mechanistic_support_score REAL,
    prediction_support_score REAL,
    ood_flag BOOLEAN NOT NULL,
    abstention_recommended_flag BOOLEAN NOT NULL,
    uncertainty_vector_ref TEXT,
    measurement_pairing_status TEXT NOT NULL,
    temporal_completeness_flag BOOLEAN NOT NULL,
    intervention_completeness_flag BOOLEAN NOT NULL,
    support_density_estimate REAL NOT NULL,
    support_domain_tag TEXT NOT NULL,
    harmonization_confidence REAL NOT NULL,
    action_label_provenance_ref TEXT,
    state_depth_category TEXT NOT NULL,
    event_type TEXT NOT NULL,
    has_expression_features BOOLEAN NOT NULL,
    expression_feature_count INTEGER NOT NULL,
    outcome_present_flag BOOLEAN NOT NULL,
    output_present_flag BOOLEAN NOT NULL,
    output_type TEXT,
    action_candidate_labels TEXT,
    action_evidence_summary TEXT
);

CREATE TABLE IF NOT EXISTS transcriptome_profiles (
    transcriptome_profile_ref TEXT NOT NULL,
    feature_space_id TEXT NOT NULL,
    feature_id TEXT NOT NULL,
    feature_name TEXT,
    value REAL NOT NULL,
    unit TEXT,
    value_type TEXT NOT NULL,
    support_score REAL NOT NULL,
    provenance_ref TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS metabolome_profiles (
    metabolome_profile_ref TEXT NOT NULL,
    feature_space_id TEXT NOT NULL,
    feature_id TEXT NOT NULL,
    feature_name TEXT,
    value REAL NOT NULL,
    unit TEXT,
    value_type TEXT NOT NULL,
    support_score REAL NOT NULL,
    provenance_ref TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS signaling_profiles (
    profile_ref TEXT NOT NULL,
    feature_space_id TEXT NOT NULL,
    feature_id TEXT NOT NULL,
    feature_name TEXT,
    value REAL NOT NULL,
    unit TEXT,
    value_type TEXT NOT NULL,
    support_score REAL NOT NULL,
    provenance_ref TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS entity_registry (
    entity_id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    source_system TEXT NOT NULL,
    source_identifier TEXT NOT NULL,
    mapping_confidence REAL NOT NULL,
    status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS action_ontology (
    action_id TEXT PRIMARY KEY,
    action_name TEXT NOT NULL,
    parent_action_id TEXT,
    level_0 TEXT NOT NULL,
    level_1 TEXT NOT NULL,
    level_2 TEXT NOT NULL,
    zone TEXT NOT NULL,
    description TEXT NOT NULL,
    required_evidence_types TEXT NOT NULL,
    allowed_output_patterns TEXT NOT NULL,
    known_pathway_links TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evidence_trace (
    evidence_trace_id TEXT PRIMARY KEY,
    cod_event_id TEXT,
    field_name TEXT NOT NULL,
    source_dataset TEXT NOT NULL,
    source_record_pointer TEXT NOT NULL,
    transformation_step TEXT NOT NULL,
    rule_or_model TEXT NOT NULL,
    reviewer TEXT,
    confidence REAL NOT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS benchmark_rows (
    cod_event_id TEXT NOT NULL,
    task_state_to_action TEXT NOT NULL,
    task_state_intervention_to_output TEXT,
    task_state_intervention_to_outcome TEXT,
    held_out_cell_type_bucket BOOLEAN NOT NULL,
    held_out_intervention_bucket BOOLEAN NOT NULL
);
